apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-p4t8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-p4t8@sha256:7e111a05427a00513619203c2518f1e7b069752dbe777eee924ac965105dcdea
        name: my-python
        resources: {}
status: {}
